#!/bin/sh

dirname=$1

if test ! -d $dirname
then
  echo "There is no directory \"$dirname\"."
else
  echo "Do you want to delete \"$dirname\"?"
  read choice
  if test $choice = y
    then
      rmdir $dirname
      echo \"$dirname\" deleted
    else
      echo \"$dirname\" not deleted
  fi
fi
